//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean NextScene
        {
            get
            {
                return SteamVR_Actions.default_NextScene;
            }
        }
        
        public virtual SteamVR_Action_Boolean MakeBeat
        {
            get
            {
                return SteamVR_Actions.default_MakeBeat;
            }
        }
        
        public virtual SteamVR_Action_Boolean CycleAddEffect
        {
            get
            {
                return SteamVR_Actions.default_CycleAddEffect;
            }
        }
        
        public virtual SteamVR_Action_Boolean CycleDeleteEffect
        {
            get
            {
                return SteamVR_Actions.default_CycleDeleteEffect;
            }
        }
        
        public virtual SteamVR_Action_Boolean ConfirmAddEffect
        {
            get
            {
                return SteamVR_Actions.default_ConfirmAddEffect;
            }
        }
        
        public virtual SteamVR_Action_Boolean ConfirmDeleteEffect
        {
            get
            {
                return SteamVR_Actions.default_ConfirmDeleteEffect;
            }
        }
    }
}
